# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
dist: bionic
latex: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8
    - g++-8
    - gfortran-8

env:
  global:
    - INSTALLMAKEFLAGS="-j 2"
    - MAKEFLAGS="-j 2"

before_install:
  - mkdir -p ~/.R/
  - echo "CXX14 = g++-8 -fPIC -flto=2" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars

script: 
  - |
    Rscript -e 'install.packages("roxygen2")'
    ./tools/rox
    R CMD build --no-build-vignettes .
    export _R_CHECK_FORCE_SUGGESTS_=false
    travis_wait 59 R CMD check --ignore-vignettes gwsem*tar.gz

after_success:
  - travis_wait 40 Rscript -e 'covr::codecov()'

after_failure:
  - cat gwsem.Rcheck/00*
