#!/bin/bash

set -ve

sudo apt-get install -yq --allow-unauthenticated --no-install-suggests --no-install-recommends \
     r-cran-testthat r-cran-roxygen2 r-cran-devtools r-cran-covr \
     r-cran-rpf r-cran-bh r-cran-rcpp r-cran-rcppeigen r-cran-stanheaders
#     r-cran-knitr r-cran-rmarkdown  # for vignettes

# Need to grab from GIT until there is a release with the plug-in API
git clone --depth 10 https://github.com/OpenMx/OpenMx.git
pushd OpenMx
make cran-install
popd
