#!/bin/bash

if [ ! -d vignettes ]; then
    echo "Must be run from the top directory"
    exit 1
fi

# Not sure why RStudio keeps changing the hashes in the knitr cache

export NOT_CRAN=true
cd vignettes
for f in *.Rmd; do
  Rscript -e "library(rmarkdown); render('$f', html_document())"
done
